// @ts-nocheck
const {
  looksLikePlaceholderSecret,
  validateSecretValue,
  validateRequiredSecrets,
} = require("../lib/secretValidation");

const HEX64 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

describe("looksLikePlaceholderSecret", () => {
  it("catches template prefixes and bracket placeholders", () => {
    for (const v of [
      "your_secret_here",
      "changeme",
      "replace-me-now",
      "test-jwt-secret-for-ci-only",
      "<REPLACE_WITH_RANDOM_SECRET>",
      "{{ secret }}",
      "EXAMPLE_VALUE",
    ]) {
      expect(looksLikePlaceholderSecret(v)).toBe(true);
    }
  });

  it("accepts real-looking secrets", () => {
    expect(looksLikePlaceholderSecret(HEX64)).toBe(false);
    expect(looksLikePlaceholderSecret("s0me-very-l0ng-randomly-generated-secret")).toBe(false);
    expect(looksLikePlaceholderSecret("")).toBe(false);
  });
});

describe("validateSecretValue", () => {
  it("returns 'not set' alone for empty values", () => {
    expect(validateSecretValue("")).toEqual(["not set"]);
    expect(validateSecretValue(undefined)).toEqual(["not set"]);
  });

  it("enforces minimum length", () => {
    expect(validateSecretValue("short", { minLength: 32 })).toEqual([
      "shorter than the 32-character minimum",
    ]);
    expect(validateSecretValue("x".repeat(32), { minLength: 32 })).toEqual([]);
  });

  it("enforces the 64-hex format when hex64 is set", () => {
    expect(validateSecretValue(HEX64, { hex64: true })).toEqual([]);
    expect(validateSecretValue("z".repeat(64), { hex64: true })).toEqual([
      "must be a 64-character hex string (32 bytes)",
    ]);
    // crypto.ts strips inline comments before validating; mirror that.
    expect(validateSecretValue(`${HEX64} # generated by setup.sh`, { hex64: true })).toEqual([]);
  });

  it("stacks placeholder + format issues", () => {
    const issues = validateSecretValue("changeme", { hex64: true });
    expect(issues).toContain("looks like a placeholder value");
    expect(issues).toContain("must be a 64-character hex string (32 bytes)");
  });
});

describe("validateRequiredSecrets", () => {
  it("returns no problems for a fully configured env", () => {
    expect(
      validateRequiredSecrets({
        JWT_SECRET: "a-properly-long-jwt-secret-value",
        NORA_API_KEY_HASH_SECRET: "a-properly-long-hash-secret-value",
        ENCRYPTION_KEY: HEX64,
      }),
    ).toEqual([]);
  });

  it("grades JWT/encryption as fail and the hash secret as warn", () => {
    const problems = validateRequiredSecrets({});
    const byEnv = Object.fromEntries(problems.map((p) => [p.env, p]));
    expect(byEnv.JWT_SECRET.severity).toBe("fail");
    expect(byEnv.ENCRYPTION_KEY.severity).toBe("fail");
    expect(byEnv.NORA_API_KEY_HASH_SECRET.severity).toBe("warn");
  });
});
